<?php

namespace ContainerBoJUaQS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmployeeController' shared autowired service.
     *
     * @return \App\Controller\EmployeeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/EmployeeController.php';

        return $container->services['App\\Controller\\EmployeeController'] = new \App\Controller\EmployeeController();
    }
}
