<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmPnNB9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmPnNB9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXmPnNB9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXmPnNB9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXmPnNB9\App_KernelDevDebugContainer([
    'container.build_hash' => 'XmPnNB9',
    'container.build_id' => 'be18abd5',
    'container.build_time' => 1605892045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmPnNB9');
