<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFCcHpXj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFCcHpXj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFCcHpXj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFCcHpXj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFCcHpXj\App_KernelDevDebugContainer([
    'container.build_hash' => 'FCcHpXj',
    'container.build_id' => 'fc604a50',
    'container.build_time' => 1605888856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFCcHpXj');
